### PR TITLE
Testing 0.10.0

### PR DESCRIPTION
**Pull request by mmrj**

### CODE REVIEW

**Comment by mmrj** [comment]
@narenranjit i'll let you know when this is ready to merge -- going to be demo'd for Will / reviewed by platform team first (but creating the PR now for our demo mtg).

**Comment by mmrj** [comment]
@narenranjit ready for merge at your convenience (not urgent or dependent on anything)

**Comment by narenranjit** [comment]
Selenium is not a bad idea, but may be overkill for this case where there's just 1 page with not much interaction. There's also a high degree of overlap with the existing mocha tests, so at some point we should review to make sure we're not testing the same things with 2 different frameworks.

I'm fine merging for the short term, but before that we should either add a basic readme indicating how the tests should be run (i.e., install the selenium add-on and and import the html file), or gitignore it.

**Comment by wglasshusain** [comment]
Good suggestions - I like the idea of a little documentation/readme on this.

FYI - I encouraged Molly to set up some Selenium here as an experiment and we're all positive about it.  I like the concept of end to end testing.  (i.e. Selenium is basically reproducing what the user is doing.)  She has been manual testing for each Flow Js release and it seems a better process to have a documented regression test suite.

**Comment by mmrj** [comment]
Thanks for the feedback, team. Checked in a readme, let me know if there are other suggestions to it.

Naren, I'll think a bit more re mocha too. For the moment, this was just automation for the regression that I currently do.

**Pull request merged**
